import Default from "./Default";
import Title from "./Title";
import Subtitle from "./Subtitle";
import ImageAnimation from "./ImageAnimation";
import Description from "./Description";
import Author from "./Author";
import Seperator from "./Seperator";
import StatisticsList from "./StatisticsList";
import StatisticalDescription from "./StatisticalDescription";
import TableCompx from "./TableCompx";
import UserAvatar from "./UserAvatar";
import UserName from "./UserName";
export { Default, Title, Subtitle, ImageAnimation, Description, Author, Seperator, StatisticsList, TableCompx, UserAvatar, UserName, StatisticalDescription };