@endpoint = http://192.168.3.210:8089


### 获取类型为indicator的所有组件
GET {{endpoint}}/api/auto/module?componentOption=indicator
Content-Type: application/json

### 获取AutoLayout Module组件
GET {{endpoint}}/api/auto/lc_low_auto_module/lowAutoModule/lowAutoModules/161
Content-Type: application/json



### 修改module组件名称
PUT  {{endpoint}}/api/auto/lc_low_auto_module
Content-Type: application/json

### 获取module组件描述数据
GET {{endpoint}}/api/auto/lc_low_auto_module
Content-Type: application/json



