@endpoint = http://192.168.3.210:8089

### 查询已入库组件 (autolayout)
GET {{endpoint}}/api/auto/module?componentOption=autolayout


### 查询已入库组件 (cart)
GET {{endpoint}}/api/auto/module?componentOption=cart

### 查询已入库组件 (indicator)
GET {{endpoint}}/api/auto/module?componentOption=indicator

### 查询已入库组件 (selector)
GET {{endpoint}}/api/auto/module?componentOption=selector

### 查询已入库组件 (layout)
GET {{endpoint}}/api/auto/module?componentOption=layout

### 查询已入库组件 (container)
GET {{endpoint}}/api/auto/module?componentOption=container

### 查询已入库组件 (presenter)
GET {{endpoint}}/api/auto/module?componentOption=presenter

### 查询已入库组件 (gateway)
GET {{endpoint}}/api/auto/module?componentOption=gateway



### 查询indicator的layout 
//GET {{endpoint}}/api/auto/lc_low_auto_module/lowAutoModule/lowAutoModules/161
GET {{endpoint}}/api/auto/lc_low_auto_module/lowAutoModule/lowAutoModules?moduleName=IndicatorsAutolayout


