@endpoint = http://localhost:3001
@endpoint = http://192.168.3.210:8089
@preview-ui = http://192.168.3.210:3001/nav-ui/#/


###### BOOT AUTO ###########
@moduleKey=2d999984-8f29-4fb3-b5e1-e2469e19f7ef
@moduleName=avatar1


### 预览
// 增加持久化，redis重新启动后，自动把原数据重新加载
GET {{endpoint}}/api/auto/boot/preview

### 生成新组件
POST {{endpoint}}/api/auto/boot/new

### 自定义配置
// 全局更新，除 {xkey, moduleName} 保留
POST {{endpoint}}/api/auto/boot/save
Content-Type: application/json

{
        "xname": "Avatar",
        "props": {
            "url":"http://local.cdnline.io/master.jpg"
        },
        "cart": "SquareCart"
}


### PageCenter
{
    "presenter": {
        "xname": "Avatar",
        "props": {
            "url":"http://local.cdnline.io/master.jpg"
        },
        "cart": "Outline"
    },
    "cart": "PageCenter"
}





### 查询所有组件
GET {{endpoint}}/api/auto/boot/list

### 加载已入库组件
//bug: 加载成功后，需显示所有数据
POST {{endpoint}}/api/auto/boot/load/{{moduleKey}}

### 删除指定的组件 
//bug: 未实现  
DELETE {{endpoint}}/api/auto/boot/load/{{moduleKey}}

### 更新指定的组件名称 [仅moduleName, name]
PUT {{endpoint}}/api/auto/boot/{{moduleKey}}
//bug:  "message": "A component with the moduleName \"undefined\" already exists"
Content-Type: application/json

{
    "moduleName": "avatar_2",
    "name": "头像"
}


### 前一个组件
POST {{endpoint}}/api/auto/boot/load/back

### 下一个组件 
POST {{endpoint}}/api/auto/boot/load/next

### 第一个组件 
POST {{endpoint}}/api/auto/boot/load/head

### 最后一个组件 
POST {{endpoint}}/api/auto/boot/load/last

### 删除指定的组件 
//未实现  
DELETE {{endpoint}}/api/auto/boot/load/{{moduleKey}}


### 初始化为一个头像组件
POST {{endpoint}}/api/auto/boot/init

### 加载已入库组件
POST {{endpoint}}/api/auto/boot/load/{{moduleKey}}

### 更新指定的组件名称 [仅moduleName, name]
PUT {{endpoint}}/api/auto/boot/{{moduleKey}}
Content-Type: application/json

{
    "moduleName": "avatar1",
    "name": "头像"
}

### 加载指定名称的组件
GET {{endpoint}}/api/auto/boot/load/by/{{moduleName}}



####### 组件变换 #######

### 页面居中
POST {{endpoint}}/api/auto/boot/do/centralize

### 克隆多一个组件
// 默认布局
POST {{endpoint}}/api/auto/boot/do/clone

### 设置子组件个数
POST {{endpoint}}/api/auto/boot/do/repeat/{:count}

### 变更layout
POST {{endpoint}}/api/auto/boot/do/switch/layout/{:moduleName}

### 变更风格
POST {{endpoint}}/api/auto/boot/do/switch/cart/{:moduleName}

### 变更选中风格
POST {{endpoint}}/api/auto/boot/do/switch/selector/{:moduleName}

### 变更组件容器
POST {{endpoint}}/api/auto/boot/do/switch/container/{:moduleName}

### 变更内置组件
POST {{endpoint}}/api/auto/boot/do/switch/presenter/{:moduleName}

### 数据绑定
POST {{endpoint}}/api/auto/boot/do/binding/{:bindingName}

### 绑定mock数据源
POST {{endpoint}}/api/auto/boot/do/mock/{:mockName}

### 追加不同的子组件
POST {{endpoint}}/api/auto/boot/do/plus/presenter/{:moduleName}

### 外加容器组件
POST {{endpoint}}/api/auto/boot/do/wrap/{:moduleName}

### 回滚至子组件
POST {{endpoint}}/api/auto/boot/do/zoomin

### 执行【zoomin】之后回滚回前一个父组件
POST {{endpoint}}/api/auto/boot/do/zoomout

### 变换为单选组件
POST {{endpoint}}/api/auto/boot/do/to/select

### 变换为多选组件
POST {{endpoint}}/api/auto/boot/do/to/multiselect

### 查询元组件[cart]属性
GET {{endpoint}}/api/auto/boot/do/within/cart/props

### 更新元组件[cart]属性值
PUT {{endpoint}}/api/auto/boot/do/within/cart

### 查询元组件[selector]属性
GET {{endpoint}}/api/auto/boot/do/within/selector/props

### 更新元组件[selector]属性值
PUT {{endpoint}}/api/auto/boot/do/within/selector

### 查询元组件[indicator]属性
GET {{endpoint}}/api/auto/boot/do/within/indicator/props

### 更新元组件[indicator]属性值
PUT {{endpoint}}/api/auto/boot/do/within/indicator

### 查询元组件[layout]属性
GET {{endpoint}}/api/auto/boot/do/within/layout/props

### 更新元组件[layout]属性值
PUT {{endpoint}}/api/auto/boot/do/within/layout

### 查询元组件[container]属性
GET {{endpoint}}/api/auto/boot/do/within/container/props

### 更新元组件[container]属性值
PUT {{endpoint}}/api/auto/boot/do/within/container

### 查询元组件[gateway]属性
GET {{endpoint}}/api/auto/boot/do/within/gateway/props

### 更新元组件[gateway]属性值
PUT {{endpoint}}/api/auto/boot/do/within/gateway




### 需要同时维护另外一个页面

### Page1 Operations

### 显示另一个预览组件（用于对预览组件变更）
GET {{endpoint}}/api/auto/boot/previewx

### 加载指定组件至操作入口
POST {{endpoint}}/api/auto/boot/loadx/{{moduleKey}}

### 加载指定组件名称至操作入口
POST {{endpoint}}/api/auto/boot/loadx/by/{{moduleName}}

### Page2 Options

### 显示另一个预览组件（用于操作选项）
GET {{endpoint}}/api/auto/boot/previewxx

### 加载指定组件至选项界面
POST {{endpoint}}/api/auto/boot/loadxx/{{moduleKey}}

### 加载指定组件至选项界面
POST {{endpoint}}/api/auto/boot/loadxx/by/{{moduleName}}




# 与第三方组件库交互
@propName=

### 查询第三方库的组件
//TODO: 转发 GET {{endpoint}}/api/auto/module?componentOption=cart
//参数名称 componentOption= 改为 type=
GET {{endpoint}}/api/auto/boot/x/modules?type=cart


### 当前预览组件入库至第三方服务
POST {{endpoint}}/api/auto/boot/x/save/{{moduleKey}}

### 组件入库至第三方服务
POST {{endpoint}}/api/auto/boot/x/save/by/{{moduleName}}

### 从第三方服务中加载组件至预览
POST {{endpoint}}/api/auto/boot/x/load/{{moduleKey}}

### 从第三方服务中加载指定组件
POST {{endpoint}}/api/auto/boot/x/load/by/{{moduleName}}


### 查询第三方服务指定组件
GET {{endpoint}}/api/auto/boot/x/modules/{{moduleName}}

### 查询第三方组件属性
GET {{endpoint}}/api/auto/boot/x/modules/{{moduleName}}/props

### 增加第三方组件属性
POST {{endpoint}}/api/auto/boot/x/modules/{{moduleName}}/props

### 移除第三方组件属性
DELETE {{endpoint}}/api/auto/boot/x/modules/{{moduleName}}/props/{{propName}}

### 增加通用属性
POST {{endpoint}}/api/auto/boot/x/props

### 为属性增加选项值
POST {{endpoint}}/api/auto/boot/x/props/{{propName}}/options

